FROM openjdk:11-slim-buster

WORKDIR /app

ENV PROFILES=dev

ARG ORIGINAL_JAR_FILE=./build/libs/delivery-service-1.0.0.jar

COPY ${ORIGINAL_JAR_FILE} delivery-service.jar

CMD ["java", "-Dspring.profiles.active=${PROFILES}", "-jar", "/app/delivery-service.jar"]
