server:
  port: 8081
spring:
  config:
    activate:
      on-profile: local,dev,prod
  application:
    name: delivery-service
  # config service settings
  cloud:
    config:
      name: delivery-service
management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh, busrefresh
